### ISSUE TITLE
Adding Product Category 

### ISSUE THREAD

**Issue by its-mateen** [pixelabs-solutions/storemanagement-backend#23]
Error to add new category
![image](https://github.com/pixelabs-solutions/storemanagement-backend/assets/48900520/d88a7089-de10-4133-89d4-9c213cf203f4)

**Comment by sohaibturk** [comment]
The category is being added correctly, but there is an issue with the payload received from the UI.

![image](https://github.com/pixelabs-solutions/storemanagement-backend/assets/97172113/60d6d414-1a20-4e8a-927e-0c9d8a5b7d8f)

**Payload Example:**

{
    "name": "New Cat",
    "parent": "107",
    "image": {
        "src": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJwAAACUCAMAAABRNbASAAAAk1BMVEX///8rOVQDuP8iMk8AHEFyeIYAADQAtv8ADzvw8PIXKkmTlqHAw8gNJEYAFT4Ar//MztLV1tpqyf+I0f8Asv8cLkzw+f+R1P+Lj5v5/P+usroAGD/29/i5vMN+hZPa3OBfZ3nm5+mcoazk9v81QlvV7/9WX3I/SmKL1/9JVGqkqbNocIC05f+e3v/H7P9Dxf8hvv8XCUxDAAAFfElEQVR4nO2ci3KiMBSGxaBAJFZbcRWVi1IRL9X3f7q1dXMBgiTR7XZnzr8znd2lHD9OLkL+Ezqd/0qb4+6tXbvTx1Qt3nK0H8xaNVj7aSvZqTtxVHU+tvIt/YRgHLQLX5Wt7/FN37pOV13O5Hy6zxZuF4GlLESsWSPeUQvtC885b5rR0gNG6mhfwtZKGmq+m2iifeF1P5rYRhnWRPvUYi2L9aabNkr3LmcbZxotKiZvVo91ejFia6SLM90mpXL31VjvhmifdGcZ3NakTW9CcTnUXHssiHSSMbsnxmxWkJdjHYXB4ExeFCSOnkttyHpb3qiI9BVkCz10WBqy87PwUa/H6bxVm9OF57qeupAnLij26VLW8OWr8XuIXQ/aiid8CFk4tga6aSpMPZfqwYLlwR60k93k5zzbI+H/TzwLDRODTDt21kvle2zZZ3kbqMeLGRwRJrv5K/2YiWrePjVlnaF6mr+gDZSo5u1ToU0vqcdPm15Y+yjeatzEEu7sygfWdB4hoU68lDYsygU49iGvc51gmxd2XvlARLuc6+nE4+cRft6Udm3nl1asThNcj/aevl68Ac348CfDuQAHcAAHcAAHcAAHcAAHcAAHcAAHcAAHcAAHcAD3s+De/i3cjMLZAlyXfYjWgvWz4byEnoc43PzMHAUNG+L5cDFNXMnCYV6r3AH8LrgtXUwvea7cwak6Ct8JN2CGGRbtiw1zSa65e1fvd0+E8+KCm3l5qQ5B8NAd56xQV3KT0waH2ytKbooSoVgBR6Vom5IXrFxZ0m2Ds74KRnDAfuDy39iRQDTd7UoBx+4Bp/oenInsaoHE9PURuqfCBYea07h5yOV/IlyQScy894s5XQ3OrKTkiy0f19muuTNv2UnF5DevjbAPDSbo9OQY4jXb6HrC9rrZ2Z6+XRx9QKdbM999S7vmBRFSDO57x5vj7tx1JjrqvkruFuIDdofqcm2UDNrL+z41v/7pzPm/Sj/qvwwCgUAgEAj0N+TFI19P0judVDPIKG6vAxxH2zwgWsJ5rV77eqOeY70oQb6NRvU4XMswcwODB6dhVI0UDfWjoMDNVo136fGBGD7S9Sstmxo+QyB8iOVsK2z8QFfdJjDTfoKgCrAvYwtNGvSPUK8c64GHahRIqnd9u/3E74C7PrrWcpdmD4R7LpyVVeemnvneiqfD4Uq0kTi8yEL1cbMdTjXSQkxOvzzhCSsvBM38kaIWbXAL1Uj+LBC2UJTCjQVs6damBvXb4HQWrNcChLjSxDd+2PJNYd8B11mxCaO0GYANB6Kxt+LpcHytXxwSy4J1YKW1lL8Fl1IKVPDvWI8mTtzB8Q/glmxcYn7/5NE5Aeu16rPhpPshPPenwbkAB3AAB3AAB3AAB3AAB3AAB3AAB3AAB3AAB3AA9yPgHl3ZDKpwwYNw4somK/XXWxOO6UUFFTeYvetm2GCfyrXkZeMcznQ1nV0oqRjprNpVrylSSiGupnci9ik1Q/yO4pwGcyu1vWPaia1C52ojdk0ihuDgqL9IyUuYmeZWjzE4nKi//CiUOzhj7rYiyYvzpIo5Gz5UDx74sUS12824D5qVWkJ0DXEU+qs27ROXxwpqNRcjHg+5yb41nB9GmJualcE/Fv1WbLeLCMUKkhd+LROObgVEIWDJb6104eiBN+3ZklL38QMlA7VRmQovf9Nlk/bSmTEdymsjfKz9ws4/wvKJe2laNYCwpCFWyIiONM0VXmKUO4SkdrTJG0UR7jXOY17PoPoIZw3VVql2NGLdnbNDS3OYIdJr/kbxC4JVWxcFmMxaJth4RrBqFRJCmBT+3RuPeHAoVOYlYm17ocI3kxf2tpZKvKA4DKS7b0papvFYQQqFgpRPLZ7kZZy/AToUw8p4HeF4AAAAAElFTkSuQmCC"
    }
}

**ISSUE:** The parent field expects an integer value representing the ID of another category.

Payload from UI:
{
    "name": "werwe",
    "parent": "NodeJS",
    "image": [""]
}

In this case, the parent field contains the string "NodeJS," which causes an error. The parent field should instead contain an integer value.


**CHANGES TO BE MADE:**
![image](https://github.com/pixelabs-solutions/storemanagement-backend/assets/97172113/355efcc7-d765-4fe5-9b80-d821874c130f)
Parent category dropdown list should be populated dynamically here.

**Comment by Wasif-kn** [comment]
Categories are populates in parent category select field, add category api is also working 
@waqih kindly check form its not adding any categories. Category ID is in the value attribute of option check screenshot

![image](https://github.com/pixelabs-solutions/storemanagement-backend/assets/63958804/ba0ecbcf-04c0-4516-a354-861bf5f61a58)

**Comment by Wasif-kn** [comment]
Remember parent category option is optional
