### ISSUE TITLE
Categories Index Response Time Fluctuate 

### ISSUE THREAD

**Issue by its-mateen** [pixelabs-solutions/storemanagement-backend#31]
storemanagement-backend.test/categories?is_rest=true

Response Time Average : 5.43 s  
![image](https://github.com/pixelabs-solutions/storemanagement-backend/assets/48900520/990be523-ad06-450c-9e96-bf794e62c179)

**Comment by sohaibturk** [comment]
Response time: 3.84 s
![image](https://github.com/pixelabs-solutions/storemanagement-backend/assets/97172113/95ba679c-e0ed-4a50-bb82-e643e8b24a2c)

**Comment by sohaibturk** [comment]
The size of the response has been reduced from 75 KB to 4.86 KB, resulting in a significant decrease. However, the response time is still 3.5 seconds, which is attributable to the WooCommerce REST API.

![image](https://github.com/pixelabs-solutions/storemanagement-backend/assets/97172113/c13d76d8-c7c0-4cfa-a4b0-7379b4462d10)
