### ISSUE TITLE
Transaction

### ISSUE THREAD

**Issue by its-mateen** [pixelabs-solutions/storemanagement-backend#52]
In Transaction Table Data should be responsive

![image](https://github.com/pixelabs-solutions/storemanagement-backend/assets/48900520/0f5929dd-c1f7-421c-92fb-1f93da929647)

**Comment by pixelabs-tech** [comment]
![image](https://github.com/pixelabs-solutions/storemanagement-backend/assets/154874466/b084e055-938b-40df-9434-8ca9350c7cec)
